name: Build "GitHub" version

on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Python # Set Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      # Run things
      - name: Build version zip
        run: |
          python zipperRelease.py "GitHub"
      - name: Upload zip
        uses: actions/upload-artifact@v4
        with:
          name: BlackICE GitHub
          path: ./BlackICE GitHub.zip
